package org.itech.labSampleTracker.enums;

public enum TrackingAction {
	COLLECT_SAMPLE_AT_FACILITY, DELIVER_SAMPLE_AT_HUB, COLLECT_SAMPLE_AT_HUB, DELIVER_SAMPLE_AT_LAB,
	COLLECT_RESULT_AT_LAB, DELIVER_RESULT_AT_FACILITY, ACCEPT_SAMPLE_AT_HUB, ACCEPT_SAMPLE_AT_LAB, REJECT_SAMPLE_AT_HUB,
	REJECT_SAMPLE_AT_LAB;
}
